n =str(input('Digite algo:'))
print(type(n))
print('é numérico?')
print(n.isnumeric())
print('é decimal?')
print(n.isdecimal())
print('é alfa?')
print(n.isalpha())
print('é alfanumérico?')
print(n.isalnum())
print('é identificador?')
print(n.isidentifier())
print('é inferior?')
print(n.islower())
print('é digito?')
print(n.isdigit())
print('é imprimivel?')
print(n.isprintable())
print('é espaço?')
print(n.isspace())
print('é título?')
print(n.istitle())
print('é superior?')
print(n.isupper())


